openapi: "3.0.0"
info:
  version: "v1"
  title: PowerXAI Ingestion Service
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:

  /data:
    post:
      summary: Endpoint to add metrics
      operationId: ingestMetrics
      tags:
        - metrics
        - ingestion
        - data
      requestBody:
          required: true
          description: Metrics data
          content:
            application/text:
              schema:
                type: string e.g (1649941817 Voltage 1.34)
          
      responses:
        'Success':
          description: Created User object with JWT authentication token
          content:
            application/json:
              schema:    
                type: object
                properties:
                  success:
                    type: boolean
                    description: status of metrics ingestion - true
                                
        'Error': 
          description: Validation error
          content:
            application/json:
              schema:    
                type: object
                properties:
                  success:
                    type: boolean
                    description: status of metrics ingestion - false

    get:
      summary: List metrics between dates
      operationId: listMetrics
      tags:
        - data
      parameters:
        - name: from
          in: query
          description: Date to query metrics from
          required: true
          schema:
            type: date
            format: ISO
      responses:
        'Success':
          description: An array of available metrics
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Readings"

components:
  schemas:
    Readings:
      type: object
      required:
        - time
        - name
        - value
      properties:
        id:
          type: string
          description: string generated by the server/database; not part of input.
        name:
          type: time
          description: time of metric
        email:
          type: name
          description: Name of metric
        value:
          type: value
          description: Value of metric
       

    